### ISSUE TITLE
Improper install command

### ISSUE THREAD

**Issue by laggycomputer** [Da532/Innocent-bot#14]
Your install command for discord.py rewrite is incorrrect. The correct form is `pip3 install git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py`.

**Comment by Da532** [comment]
..it just isn’t though for this build.

**Comment by laggycomputer** [comment]
No, it is correct. The egg part is necessary to tell pip what to do with the cloned repo.

`pip` and `pip3` vary over operating systems. I'd strongly recommend you add a note about such.
