### ISSUE TITLE
mall DMs only those with which you have DMs open

### ISSUE THREAD

**Issue by ghost** [Da532/Innocent-bot#28]
How to reproduce this issue: Go to a server which you don't know the members of (or dont have dms open with), do [prefix]mall owo, it will only dm you (which is not possible). 
What I did to fix it: try to create DM:`channel = await user.create_dm()
                await channel.send(message)`, did the same thing as before.

**Comment by Soheab** [comment]
this is not a issue, you can't just dm whoever you want.

**Comment by ghost** [comment]
this is one; it is supposed to dm your guild mates. It is in the code and also mentioned in readme

**Comment by ghost** [comment]
i FIXED IT MYSELF, commiting
