### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by Soheab** [Da532/Innocent-bot#35]
As per [this](https://github.com/Rapptz/discord.py/commit/427e387a2f487cf27d4a7ed5b49cc4c4bcae58ed) commit to the discord.py library,  all non-bot/selfbot/userbot methods are deprecated. 

That means this repository should be archived and users should be told to not use this code anymore and not get any support regarding this.

**Update:** Per [this](https://github.com/Rapptz/discord.py/commit/54288879e28cc63eefce33311ec393a4eed476c4) commit all user bot methods were officially removed for the next and major version of discord.py; 2.0

**Comment by Aethese** [comment]
discord.py is also no longer supported so you shouldn't use it until slash commands are forced to be used
