### ISSUE TITLE
I just need help with setup

### ISSUE THREAD

**Issue by ghost** [Da532/Innocent-bot#5]
i am having issues with installing "discord.py"

**Comment by jinxatstatefarm** [comment]
im just having issues with almost every aspect of getting the bot setup

**Comment by hax4dazy** [comment]
Yeah i too am having this issue. Gonna try reinstalling python perhaps that will fix it. Or discord nuked their discord.py

**Comment by hax4dazy** [comment]
UPDATE: I got it to install by uninstalling python and reinstalling it and selecting every option. If you still cant get it to work ill make a vid about it

**Comment by Liskomies** [comment]
> UPDATE: I got it to install by uninstalling python and reinstalling it and selecting every option. If you still cant get it to work ill make a vid about it

hey. can you help me out a little?

**Comment by maxichrome** [comment]
Closing this issue because it's not an issue with the project. Please use [Google](https://google.com) and your head.
