### ISSUE TITLE
Start banning on start rather than on command

### ISSUE THREAD

**Issue by LoganRogers1337** [Da532/Innocent-bot#6]
It would be nice if there was an option to have the bot immediately start banning when it starts, rather than having to run a command first.

**Comment by maxichrome** [comment]
If you'd like to start a PR for this that would be great. Issues aren't for general advice and tips. I'll edit your message as a feature request instead.

**Comment by Da532** [comment]
I think this sounds unsafe and messier as you'd have to specify the ID and mess around in the raw code which I really don't want users doing.
