### ISSUE TITLE
Rename-all command doesn't work.

### ISSUE THREAD

**Issue by Soheab** [Da532/Innocent-bot#8]
title...........

**Comment by maxichrome** [comment]
There will be an update for Innocent coming out soon. The current version is unsupported. Please watch the repository and you'll be notified once the next release comes out. Thank you!

**Comment by Soheab** [comment]
> There will be an update for Innocent coming out soon. The current version is unsupported. Please watch the repository and you'll be notified once the next release comes out. Thank you!

Ah ty

**Comment by maxichrome** [comment]
@Soheab If you're still having this issue, could you please describe more? Is there any error message or does nothing happen? Please let us know!

**Comment by Soheab** [comment]
Oh hey, sry for late reply but this is all fixed. Thanks!
